config/routes.rb
Rails.application.routes.draw do
  
  resources :sites

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :places

  get 'map' => "maps#map"

  root 'pages#home'
  get 'pages/contact'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-main">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="small-logo-container">
            <%= link_to "GTour", root_path, class: "small-logo" %>
          </div>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-main">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to root_path do %>
          <span class="glyphicon glyphicon-home"></span> Home
          <% end %>
        </li>
        <li>
          <%= link_to map_path do %>
          <span class="glyphicon glyphicon-map-marker"></span> Map</a>
          <% end %>
        </li>
        <li>
          <%= link_to sites_path do %>
          <span class="glyphicon glyphicon-globe"></span> Explore</a>
          <% end %>
        </li>
        <li>
          <%= link_to pages_contact_path do %>
          <span class="glyphicon glyphicon-briefcase"></span> Contact</a>
          <% end %>
        </li>
         
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :head %>
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.css' rel='stylesheet' />
  <%= csrf_meta_tags %>
</head>
<body>


	<%= render "layouts/navbar" %>
<%= yield %>


</body>
</html>